# docker-compose up -d --build
version: '3'
services:
  charts:
    build: 
      context: .
    ports:
     - "3456:3456"
    environment:
      WATERMARK: "true"
      PORT: 3456
    restart: unless-stopped
