# docker-compose -f docker-compose-nowm.yml up -d --build
# (nowm == no watermark)
version: '3'
services:
  charts-nowm:
    build: 
      context: .
    ports:
     - "3457:3457"
    environment:
      WATERMARK: "false"
      PORT: 3457
    restart: unless-stopped
